# Generated by Django 5.1.4 on 2024-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_account_id',
            field=models.CharField(default='S000001', max_length=10, unique=True),
        ),
    ]
