# Generated by Django 5.1.4 on 2024-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sellerprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_account_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
